
#################################################
### THIS FILE WAS AUTOGENERATED! DO NOT EDIT! ###
#################################################
# file to edit: dev_nb/12_unit_test.ipynb

def test(a, b, cmp, cname=None):
    if cname is None: cname = cmp.__name__
    assert cmp(a,b), f'{cname}\n a \n b'

def test_eq(a, b): test(a, b, operator.eq, '==')